### ISSUE TITLE
Demographic Parity

### ISSUE THREAD

**Issue by kschweig** [socialfoundations/error-parity#6]
Hello,

amazing package, I use it a lot lately!
I wanted to ask, whether it is scheduled in the near future to add demographic parity as a constraint, I would need it for a current project of mine using this package.

Thanks!

**Comment by AndreFCruz** [comment]
Thanks for using the package!
Good point. It should be straightforward to implement. I'll look into it and hopefully release a new version shortly.

**Comment by AndreFCruz** [comment]
@kschweig `constraint="demographic_parity"` should now be available on `error-parity>=0.3.9`

I implemented some tests but do let me know if you find any bugs! 🐞
